_target_: src.models.modelmodule.ModelModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.MSELoss

model_name: NeRF

net:
  _target_: src.models.components.NeRFNet.NeRF
  input_dim: 3 
  num_frequencies: 64
  hidden_dim: 256
  num_layers: 5
  output_dim: 1

sampling:
  method: hybrid_sampling  # Options: no_sampling, error_based, gradient_based, hybrid_sampling
  sample_ratio: 0.1
  error_ratio: 0.7

data_shape: ${data.data_shape}

compile: false