_target_: src.models.modelmodule.OCINRTraining

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.MSELoss

net:
  _target_: src.models.components.OC_FFNet.OCFourierFeatureNetwork
  input_dim: 2
  mapping_size: 256
  hidden_dim: 256
  output_dim: 1
  num_layers: 3
  dropout_rate: 0.5
  activation: "GELU"
  block_type: "residual"
  num_steps: 12
  total_time: 1.0
  ot_lambda: 0.001
  sigma: 10.0
  final_activation: null

compile: false

ntk_analysis: true
ntk_frequency: 2
ntk_top_k: 10
ntk_subset_size: 1024
ntk_subset_stride: 1
ntk_normalize: "trace"